"""add_note_to_shifts

Revision ID: 841a48bb22da
Revises: 091d3c42e659
Create Date: 2026-07-04 23:13:26.725477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841a48bb22da'
down_revision: Union[str, None] = '091d3c42e659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'note')
    # ### end Alembic commands ###
