"""add description to day off request

Revision ID: a77abba702cf
Revises: 991a7b440272
Create Date: 2026-06-24 21:56:15.612124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77abba702cf'
down_revision: Union[str, None] = '991a7b440272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_off_requests', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_off_requests', 'description')
    # ### end Alembic commands ###
